kind: PersistentVolume
apiVersion: v1
metadata:
  name: pervol1
spec:
  accessModes:
      - ReadWriteOnce
#      - ReadOnlyMany
#      - ReadWriteMany
  capacity:
    storage: 500Mi
  hostPath:
    path: /mnt/c/Users/haier/data
  persistentVolumeReclaimPolicy: Delete
#  awsElasticBlockStore:
#    volumeID: <volume-id>
#    fsType: ext4

