kind: Deployment
apiVersion: apps/v1
metadata:
  name: rud
  namespace: prod
  labels:
    app: rudapp
    type: frontend
    env: production
  annotations:
    createdBy: "Abdul Qadir"
spec:
  replicas: 6
  selector:
    matchLabels:
      app: rudapp
      type: frontend
  template:
    metadata:
      name: rud
      labels:
        app: rudapp
        type: frontend
    spec:
      containers:
      - name: con1
        image: aamirpinger/flag
        ports:
        - containerPort: 80
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
