kind: Pod
apiVersion: v1
metadata:
  name: secretvolume
spec:
  volumes:
  - name: scvol
    secret:
      secretName: sff
  containers:
  - name: con1
    image: aamirpinger/flag
    volumeMounts:
    - name: scvol
      mountPath: /data
