kind: Pod
apiVersion: v1
metadata:
  name: secretpod
spec:
  containers:
  - name: con1
    image: aamirpinger/helloworld
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: secret-appname
